#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Otherwise, displays the number
#In a list format
for numbers in {1..100}
do
    if [ $((numbers%3)) -eq 0 ] && [ $((numbers%5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((numbers%3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((numbers%5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$numbers"
    fi
done