#!/usr/bin/env bash
#  script to display "Best School" and "Hi"
counter="0"
while [ $counter -lt 10 ]
do
    echo "Best School"
    if ((counter == 8))
    then
        echo "Hi"
    fi
    counter=$((counter+1))
done