#!/usr/bin/env bash
#loop 10 iteration and three specific conds
counter="0"
while [ $counter -lt 10 ]
do
    if ((counter == 3))
    then
        echo "bad luck"
    elif ((counter == 7))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    counter=$((counter+1))
done
