#!/usr/bin/env bash
# Displays numbers  1 to 20 in addition to:
#   "bad luck from China"  4th iteration
#   "bad luck from Japan"  9th iteration
#   "bad luck from Italy"  17th loop iteration

loop=1

while [ $loop -le 20 ]
do
  echo "$loop"
  case $loop in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  loop=$(( loop+1 ))
done