#!/usr/bin/env bash
# script to display time for 12 hrs and 50min
hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        minutes=$((minutes+1))
    done
    hours=$((hours+1))
done